### ISSUE TITLE
Change temp sessionID to more robust UUID

### ISSUE THREAD

**Issue by delaneyj** [gmosx/dart-wamp#2]
client.dart line 12...

```
sessionId = rnd.nextInt(99999).toString(); // TODO: use some kind of hash.
```

If you used the http://pub.dartlang.org/packages/uuid package on pub and did

```
sessionID = uuid.v4(); // something like '110ec58a-a0f2-4ac4-8393-c866d813b8d1'
```

instead it would be far more useful as a key for store Client and use elsewhere.  It also avoid the high likelihood of collisions from the current schema.

**Comment by gmosx** [comment]
We now use UUID.v4 as default, and it's overridable (WebHandler.generateSessionId).
